#!/bin/bash

curl -i -X "PUT" "http://localhost:8000/task/v1/task/$2" \
	-H 'Accept: application/json' \
	-H 'Content-Type: application/json' \
	-H 'Authorization: Bearer '"$1" \
	-d '{"title":"Read a book", "description": "Bar", "done": "true"}'
